# Example configuration file
prometheus:
  port: 63512 
  enabled: true
graphite:
  server: graphite-v10-dev.internal.apiconnect.cloud.ibm.com
  port: 2003
  enabled: false
nets:
  datapower:
    enabled: true
    username: admin
    namespace: apic-gateway
  product:
    enabled: true
    username: trawler-monitor
    namespace: apic-management
