apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: trawler
  files:
  - config.yaml
  - secret.yaml
resources:
- deployment.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml

namespace: apic-monitoring
