apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trawler-view
  namespace: apic-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: trawler
  namespace: apic-monitoring
